In [2]:
10**5

100000

In [3]:
res = []
res.append(0)
res

[0]

In [4]:
res.append(0)
res.append(0)

In [5]:
res

[0, 0, 0]

In [6]:
res.append([0,0])

In [7]:
res

[0, 0, 0, [0, 0]]

In [15]:
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))


# softmax 
# [0,1] 
# sum 1 
x = [1,2,3,4,6]
res = softmax(x)
print(res.min()>0)
print(res.max()<1)
print(sum(res) == 1)

# step 3
x = [1,2,3,4,1000000]
res = softmax(x)
print(res)

# normalization [0,1]
case 1(x - x.min)/(x.max-x.min)
# standardation  [-mean,/std]
case2 

case0 



True
True
True
[ 0.  0.  0.  0. nan]


/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/405494890.py:3: RuntimeWarning: overflow encountered in exp
  return np.exp(x)/np.sum(np.exp(x))
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/405494890.py:3: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x)/np.sum(np.exp(x))


In [13]:
x = [1,2,3]
softmax(x)

array([0.09003057, 0.24472847, 0.66524096])

In [ ]:
def softmax(x):
    res = 0
    for i in x:
        res += np.exp(x)
    return exp(x)/res





In [18]:
import numpy as np
def softmax(x):
    
    f = np.sum(np.exp(x))
    return np.exp(x)/f

x = [1,2,3,4,100000]
softmax(x)

/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:4: RuntimeWarning: overflow encountered in exp
  f = np.sum(np.exp(x))
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:5: RuntimeWarning: overflow encountered in exp
  return np.exp(x)/f
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:5: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x)/f


array([ 0.,  0.,  0.,  0., nan])

In [20]:
import numpy as np
def softmax(x):
    
    f = np.sum(np.exp(x))
    return np.exp(x)/f

x = [1,2,3,4,100000]
softmax(x-np.max(x))

array([0., 0., 0., 0., 1.])

In [22]:
np.exp(-10000000)

0.0

In [24]:
s = [1,5,3,4]
sorted(s)

[1, 3, 4, 5]

In [25]:
a = [1,2,3,4]

s = set(a)

In [26]:
s

{1, 2, 3, 4}

In [27]:
s = set(range(8))

In [28]:
s

{0, 1, 2, 3, 4, 5, 6, 7}

In [2]:
for r in range(9):
    for c in range(9):
        idx = (r // 3) * 3 + c // 3 #这个处理，不用单独写3x3
        print(r,c,idx)
        

0 0 0
0 1 0
0 2 0
0 3 1
0 4 1
0 5 1
0 6 2
0 7 2
0 8 2
1 0 0
1 1 0
1 2 0
1 3 1
1 4 1
1 5 1
1 6 2
1 7 2
1 8 2
2 0 0
2 1 0
2 2 0
2 3 1
2 4 1
2 5 1
2 6 2
2 7 2
2 8 2
3 0 3
3 1 3
3 2 3
3 3 4
3 4 4
3 5 4
3 6 5
3 7 5
3 8 5
4 0 3
4 1 3
4 2 3
4 3 4
4 4 4
4 5 4
4 6 5
4 7 5
4 8 5
5 0 3
5 1 3
5 2 3
5 3 4
5 4 4
5 5 4
5 6 5
5 7 5
5 8 5
6 0 6
6 1 6
6 2 6
6 3 7
6 4 7
6 5 7
6 6 8
6 7 8
6 8 8
7 0 6
7 1 6
7 2 6
7 3 7
7 4 7
7 5 7
7 6 8
7 7 8
7 8 8
8 0 6
8 1 6
8 2 6
8 3 7
8 4 7
8 5 7
8 6 8
8 7 8
8 8 8


In [3]:
1 //3

0

In [4]:
2 // 3

0

In [6]:
s = 123
ss = str(s)

In [7]:
ss

'123'

In [13]:
ss.split('',1)

ValueError: empty separator

In [14]:
-123 %10

7

In [15]:
123 % 10

3

In [16]:
123 // 10

12

In [17]:
s = "A man, a plan, a canal: Panama"

In [18]:
s.lower()

'a man, a plan, a canal: panama'