In [2]:
10**5

100000

In [3]:
res = []
res.append(0)
res

[0]

In [4]:
res.append(0)
res.append(0)

In [5]:
res

[0, 0, 0]

In [6]:
res.append([0,0])

In [7]:
res

[0, 0, 0, [0, 0]]

In [15]:
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))


# softmax 
# [0,1] 
# sum 1 
x = [1,2,3,4,6]
res = softmax(x)
print(res.min()>0)
print(res.max()<1)
print(sum(res) == 1)

# step 3
x = [1,2,3,4,1000000]
res = softmax(x)
print(res)

# normalization [0,1]
case 1(x - x.min)/(x.max-x.min)
# standardation  [-mean,/std]
case2 

case0 



True
True
True
[ 0.  0.  0.  0. nan]


/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/405494890.py:3: RuntimeWarning: overflow encountered in exp
  return np.exp(x)/np.sum(np.exp(x))
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/405494890.py:3: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x)/np.sum(np.exp(x))


In [13]:
x = [1,2,3]
softmax(x)

array([0.09003057, 0.24472847, 0.66524096])

In [ ]:
def softmax(x):
    res = 0
    for i in x:
        res += np.exp(x)
    return exp(x)/res





In [18]:
import numpy as np
def softmax(x):
    
    f = np.sum(np.exp(x))
    return np.exp(x)/f

x = [1,2,3,4,100000]
softmax(x)

/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:4: RuntimeWarning: overflow encountered in exp
  f = np.sum(np.exp(x))
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:5: RuntimeWarning: overflow encountered in exp
  return np.exp(x)/f
/var/folders/qp/zbmlljzd6m33mg4gt0zdfwjryvxfkf/T/ipykernel_50610/3728522884.py:5: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(x)/f


array([ 0.,  0.,  0.,  0., nan])

In [20]:
import numpy as np
def softmax(x):
    
    f = np.sum(np.exp(x))
    return np.exp(x)/f

x = [1,2,3,4,100000]
softmax(x-np.max(x))

array([0., 0., 0., 0., 1.])

In [22]:
np.exp(-10000000)

0.0

In [24]:
s = [1,5,3,4]
sorted(s)

[1, 3, 4, 5]

In [25]:
a = [1,2,3,4]

s = set(a)

In [26]:
s

{1, 2, 3, 4}

In [27]:
s = set(range(8))

In [28]:
s

{0, 1, 2, 3, 4, 5, 6, 7}