In [2]:
s = [3,2,5,1,4]
s.sort()
s

[1, 2, 3, 4, 5]

In [14]:
for i in range(len(s)-1, -1, -1):
    print(i)


4
3
2
1
0


In [15]:
3 ^ 1

2

In [16]:
s = [1,5,3,6,2]

In [17]:
sorted(s)

[1, 2, 3, 5, 6]

In [18]:
sorted(s,reverse=True)

[6, 5, 3, 2, 1]

In [19]:
boxTypes = [[5,10],[2,5],[4,7],[3,9]]

In [20]:
sorted(boxTypes, key=lambda x:x[0])

[[2, 5], [3, 9], [4, 7], [5, 10]]

In [21]:
sorted(boxTypes, key=lambda x:x[1])

[[2, 5], [4, 7], [3, 9], [5, 10]]

In [22]:
sorted(boxTypes, key=lambda x:x[0], reverse=True)

[[5, 10], [4, 7], [3, 9], [2, 5]]

In [1]:
nums = [1,2,3,4,5,6]

presum = 0
arr = [0]*len(nums)
for i, num in enumerate(nums):
    presum += num
    arr[i] = presum
    
print(arr)
    

[1, 3, 6, 10, 15, 21]


In [2]:
import numpy as np 

# define a large number N

N = 1000
count = 0 
for i in range(N):
    sample =  np.random.rand(i, 2)
    if sample[0] ** 2 + samples[1] ** 2 <= 1: 
        count += 1

pi_value = count/N 

IndexError: index 0 is out of bounds for axis 0 with size 0

In [5]:
sample =  np.random.rand(1, 2)

In [4]:
sample

array([], shape=(0, 2), dtype=float64)

In [6]:

import numpy as np 

# define a large number N

N = 100
count = 0 
for i in range(1, N):
    sample =  np.random.rand(i, 2)
    if sample[0] ** 2 + samples[1] ** 2 <= 1: 
        count += 1

pi_value = count/N 

NameError: name 'samples' is not defined

In [7]:
np.random.rand(1, 2)

array([[0.47618718, 0.24066935]])

In [43]:
import numpy as np 
N = 10000000 1 million 
samples = np.random.rand(N,2) # random! 
# define a large number N

count = 0 
for i in range(N):
    if samples[i][0] ** 2 + samples[i][1] ** 2 <= 1:  #2D array!
        count += 1 # plus + 1

pi_value = count/N*4 
print([pi_value])

# the random number is [0,1], 

[3.272]


In [40]:
samples

array([[0.50155454, 0.02177555],
       [0.61733715, 0.60150935],
       [0.17233594, 0.18383559],
       ...,
       [0.38241116, 0.93059768],
       [0.17936087, 0.16084908],
       [0.01960786, 0.917246  ]])

In [20]:
sample = np.random.rand(100, 2)

In [25]:
sample[0,:]**2 + sample[1,:]**2 

array([0.60500104, 0.15996081])

In [23]:
sample[1]

array([0.61814281, 0.23250049])

In [44]:
s = 'abc'




In [45]:
s

'abc'

In [47]:
ss = list(s)

In [48]:
ss

['a', 'b', 'c']

In [49]:
ss[0] = 'd'

In [50]:
ss

['d', 'b', 'c']

In [55]:
''.join(ss)

'dbc'

In [56]:
        memo = {0:0, 1:1, 2:1}

In [57]:
memo

{0: 0, 1: 1, 2: 1}

In [58]:
[2,2,3,3,3,4]

In [59]:
s.pop(2)

3

In [62]:
s = [2,2,3,3,3,4]

In [63]:
s

[2, 2, 3, 3, 3, 4]

In [64]:
s.remove(3)

In [65]:
s

[2, 2, 3, 3, 4]

In [3]:
intervals = [[4,3],[2,6],[8,10],[15,18]]

s = sorted(intervals)

In [4]:
s

[[2, 6], [4, 3], [8, 10], [15, 18]]