In [1]:
import numpy as np
from sklearn import metrics
y = np.array([1, 1, 2, 2])
pred = np.array([0.1, 0.4, 0.35, 0.8])
fpr, tpr, thresholds = metrics.roc_curve(y, pred, pos_label=2)
metrics.auc(fpr, tpr)

0.75

In [2]:
fpr

array([0. , 0. , 0.5, 0.5, 1. ])

In [3]:
tpr

array([0. , 0.5, 0.5, 1. , 1. ])

In [4]:
thresholds

array([1.8 , 0.8 , 0.4 , 0.35, 0.1 ])